version: '3'
services:
  app:
    container_name: qcs_example_php
    build: docker
    ports:
      - "${QCS_EXAMPLE_PORT}:80"
      - "2443:443"
    volumes:
      - ./:/var/www/html/
    environment:
      - QCS_ENDPOINT=${QCS_ENDPOINT}
      - QCS_CUSTOMER_ID=${QCS_CUSTOMER_ID}
      - QCS_SHOP_ID=${QCS_SHOP_ID}
      - QCS_SHOP_SECRET=${QCS_SHOP_SECRET}
